### ISSUE TITLE
More strategies

### ISSUE THREAD

**Issue by marvson** [matthewdias/kitsu-updater#1]
Hello, I was trying to find an extension to track episodes for kitsu (hummingbird when I started to look for it) for chrome web store. Your extension is very great, but I watch animes in a site not listed in your plugin. It's in another language. It would be really good if you could add support to add more sources (the source that I watch already match with the kitsu titles).

**Comment by matthewdias** [comment]
@marvson What source do you use?

**Comment by marvson** [comment]
Mostly http://www.superanimes.com/ and http://www.animakai.tv/ Thanks for answering.

**Comment by matthewdias** [comment]
- [x] http://www.superanimes.com/ 
- [x] http://www.animakai.tv/
- [x] https://ww1.gogoanime.io/
- [x] https://9anime.to/
- [x] https://vrv.co/

**Comment by matthewdias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kitsu-updater](https://trello.com/c/D5kbYqQB/15-kitsu-updater)

**Comment by tejassharma96** [comment]
how necessary are the next and previous functions in media-strategies? I think almost every source I've looked at has had them defined but they don't seem super important to the functionality of this. I wanted to add VRV support, and I couldn't figure out a way to go to the next and previous episodes.

**Comment by matthewdias** [comment]
If there's no way to achieve it don't worry about it. They're used in a separate project. They don't matter for kitsu-updater @tejassharma96
