### ISSUE TITLE
No UI change after logging in

### ISSUE THREAD

**Issue by tejassharma96** [matthewdias/kitsu-updater#3]
When I log in, nothing appears to happen in the extension. However, if I go to cruncyroll and watch something, then the extension updates correctly and lets me scrobble to my kitsu account. The code looks like it's meant to change to show a us our profile picture and username once we're logged in, and it clearly isn't doing that. At first I thought it might be because I was using vivaldi instead of chrome, which can be buggy sometimes so I tried on chrome and it still didn't work.

**Comment by tejassharma96** [comment]
Restarting the browser doesn't change anything visually, but I can confirm that I'm still logged in after doing so

**Comment by wopian** [comment]
If you're logged in it shows your avatar and username in the menu:

![](http://i.imgur.com/jYeH5sv.png)

**Comment by tejassharma96** [comment]
Yeah I figured it was meant to, but it doesn't for me. Just continues to show the username and password input fields as if I wasn't, even though I can scrobble to my account.

**Comment by matthewdias** [comment]
that's odd. do you think you could inspect the popup and see if there are any errors?

**Comment by tejassharma96** [comment]
You need a null check :-)
`Error in event handler for (unknown): TypeError: Cannot read property 'avatar' of null
    at sendMessage (chrome-extension://maaganaggnnofcmkongapkhkjlehedfj/js/options.js:88:25)`
Indeed, after setting an avatar it now shows up.

**Comment by matthewdias** [comment]
ahh, i was supposed to fix that but forgot 😞  thanks for the reminder.

**Comment by matthewdias** [comment]
fixed in latest release
