### ISSUE TITLE
Masterani.me updating isn't working

### ISSUE THREAD

**Issue by tejassharma96** [matthewdias/kitsu-updater#4]
I was trying to use masterani.me, but the add-on was just showing me the regular home page when watching anime. I went through the source code and updated the strategy for masterani.me in your media-strategies repo. Please could you accept the pull request so I can update from masterani.me. https://github.com/matthewdias/media-strategies/pull/1

**Comment by matthewdias** [comment]
yeah, sorry i saw it, just didn't get to it today. i'll tweak the code a bit and get it in tomorrow. thanks for the pull requests!

**Comment by tejassharma96** [comment]
Cool, just wanted to make sure you had seen it :-)

**Comment by matthewdias** [comment]
thanks again!

**Comment by tejassharma96** [comment]
:)

**Comment by tejassharma96** [comment]
So I updated the extension but it appears it is still not working. Does it work on your end?

**Comment by matthewdias** [comment]
Ah! i forgot to add it to the settings page.

**Comment by tejassharma96** [comment]
For 9anime? Cool, but it doesn't work for masterani either on my end.

**Comment by tejassharma96** [comment]
Do you think it could be an http vs https situation?

Update: On checking what document.URL returns in the console, it is indeed a http vs https situation. Gonna make a pull request that should hopefully change that.

**Comment by matthewdias** [comment]
ah, they switched to https. ill update all the urls to handle both http and https.
edit: just saw ur comment. nice catch.

**Comment by tejassharma96** [comment]
Ah ok was about to make the pull request but it'll probably be faster if you just do it haha
9anime is https too fyi

**Comment by matthewdias** [comment]
alright i've fixed the issues with masterani and 9anime, update should roll out shortly.

**Comment by tejassharma96** [comment]
Confirmed working on both masterani and 9anime
